bot:
  attack: aoe_skill
  map: the_path_of_time_1_for_mage
channel_change:
  mode: 'true'
health_monitor:
  add_hp_percent: 0
  add_mp_percent: 0
key:
  aoe_skill: shift
  directional_attack: ''
  jump: alt
  return_home: ''
  teleport: ''
